language: generic

dist: trusty
sudo: required

git:
  depth: 3

install:
  - python3 --version
  - sudo apt-get install -qq python3-pip
  - sudo apt-get install -qq coinor-cbc
  - sudo pip3 install pulp

script:
  - ./run-tests

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
