language: python

dist: trusty
sudo: required

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

git:
  depth: 3

install:
  - pip3 install pulp==2.1

script:
  - ./run-tests

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
